package com.myspace.finalproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Lecture implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label("Speaker")
	private com.myspace.finalproject.Speaker speaker;
	@org.kie.api.definition.type.Label("Title")
	private java.lang.String title;
	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("Publish")
	private java.lang.Boolean publish;
	@org.kie.api.definition.type.Label("CreatedAt")
	private java.lang.String createdAt;

	@org.kie.api.definition.type.Label(value = "contents")
	private java.lang.String contents;

	public Lecture() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public com.myspace.finalproject.Speaker getSpeaker() {
		return this.speaker;
	}

	public void setSpeaker(com.myspace.finalproject.Speaker speaker) {
		this.speaker = speaker;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Boolean getPublish() {
		return this.publish;
	}

	public void setPublish(java.lang.Boolean publish) {
		this.publish = publish;
	}

	public java.lang.String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.lang.String createdAt) {
		this.createdAt = createdAt;
	}

	public java.lang.String getContents() {
		return this.contents;
	}

	public void setContents(java.lang.String contents) {
		this.contents = contents;
	}

	public Lecture(java.lang.Integer id,
			com.myspace.finalproject.Speaker speaker, java.lang.String title,
			java.lang.String type, java.lang.Boolean publish,
			java.lang.String createdAt, java.lang.String contents) {
		this.id = id;
		this.speaker = speaker;
		this.title = title;
		this.type = type;
		this.publish = publish;
		this.createdAt = createdAt;
		this.contents = contents;
	}

}