package com.myspace.finalproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Speaker implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Id")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Position")
	private java.lang.String position;
	@org.kie.api.definition.type.Label(value = "CreatedAt")
	private java.lang.String createdAt;

	public Speaker() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getPosition() {
		return this.position;
	}

	public void setPosition(java.lang.String position) {
		this.position = position;
	}

	public java.lang.String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(java.lang.String createdAt) {
		this.createdAt = createdAt;
	}

	public Speaker(java.lang.Integer id, java.lang.String name,
			java.lang.String position, java.lang.String createdAt) {
		this.id = id;
		this.name = name;
		this.position = position;
		this.createdAt = createdAt;
	}

}